"""Record a SONIC-executed motion clip - the entry point of the data pipeline.

A clip is one motion (walk, crouch-walk, strafe, ...) generated by `planner_sonic.onnx`,
replayed at 50 Hz through the frozen SONIC controller in MuJoCo, with every tick recorded:

  * what the reference asked for (`q_cmd`) and what the robot actually did (`q_act`),
  * base pose/velocity and foot contact flags,
  * the achieved body envelope (fitted from mesh samples) every few ticks - the raw material
    for `R(t) -> M(t)`, the robot's motion-capability manifold.

Everything downstream (dataset windows, primitive labels, manifold extraction) is built from
these files, so the recorded `q_act` is the ground truth: the frozen controller is path
dependent and silently ignores parts of a reference, and the achieved motion is what is
actually executable.

    python3 -m manifold_motion.clip --mode 2 --target-vel 1.0 --seconds 4
    python3 -m manifold_motion.clip --height 0.90 --out reports/manifold_motion/clips
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import dataclass, asdict
from pathlib import Path

import mujoco
import numpy as np

from . import constants as C
from .body_envelope import fit_ellipsoid, landmark_offsets, read_landmarks
from .env import G1FlatEnv
from .planner import SonicPlanner
from .reference import CROUCH_DIRECTION, PlannedReference
from .sonic import SonicController


@dataclass
class Segment:
    """One commanded segment of a random walk: travel direction, body heading, speed."""

    duration: float
    movement: tuple = (1.0, 0.0, 0.0)
    facing: tuple = (1.0, 0.0, 0.0)
    target_vel: float = 1.0


@dataclass
class ClipConfig:
    seconds: float = 4.0
    warmup_seconds: float = 0.4
    mode: int = 2                     # planner motion mode (2 = walk in the release)
    target_vel: float = -1.0          # -1 leaves it to the planner
    height: float = -1.0              # -1 = normal walking height
    movement: tuple = (1.0, 0.0, 0.0)
    facing: tuple = (1.0, 0.0, 0.0)
    context_from: str = "state"       # what the planner sees: the robot ("state") or the clip
                                      # being replayed ("reference")
    schedule: list | None = None      # list[Segment]: a random walk; overrides the single command
    crouch: float = 0.0               # joint-space crouch offset on top of the planned gait
                                      # (the planner's own `height` input is a no-op in this
                                      # release: measured identical output for -1 and 0.75)
    replan_every: int = 5             # control ticks between plan calls (10 Hz)
    envelope_stride: int = 5          # control ticks between envelope fits
    fall_height: float = 0.30         # below this the robot is on the ground, not crouching
    walk_distance: float = 0.3        # forward distance above which the clip actually moved


class ClipRecorder:
    """One robot, one motion clip, one file: what was asked for vs what happened."""

    def __init__(self, scene_path=C.FLAT_SCENE):
        self.env = G1FlatEnv(scene_path)
        self.controller = SonicController()
        self.planner = SonicPlanner()
        self.reference: PlannedReference | None = None

    # -- recording ---------------------------------------------------------
    def run(self, cfg: ClipConfig) -> dict:
        warmup = int(round(cfg.warmup_seconds / C.CONTROL_DT))
        ticks = warmup + int(round(cfg.seconds / C.CONTROL_DT))
        self.env.reset()
        self.controller.reset()
        offsets = {k: np.array(v) for k, v in landmark_offsets(self.env.model, self.env.data).items()}
        self.reference = PlannedReference.from_plan(
            self.planner, self._context(), mode=cfg.mode, movement=cfg.movement,
            facing=cfg.facing, target_vel=cfg.target_vel, height=cfg.height)
        self._apply_crouch(cfg.crouch)

        log: dict[str, list] = {k: [] for k in
                                ("t", "q_cmd", "q_act", "dq_act", "base_pos", "base_quat",
                                 "base_lin_vel", "base_ang_vel", "contact", "cmd")}
        seg_index, seg_start = 0, 0.0
        env_t: list[float] = []
        env_center: list[np.ndarray] = []
        env_semi: list[np.ndarray] = []
        env_top: list[float] = []

        wall = time.perf_counter()
        for tick in range(ticks):
            state = self.env.state()
            self.controller.append_state(state["q_hw"], state["dq_hw"], state["base_quat"],
                                         state["base_ang_vel"])
            if tick < warmup:                                   # stand still, let SONIC settle
                action, q_des = np.zeros(29), C.DEFAULT_ANGLES.copy()
            else:
                # elapsed must be in seconds: the schedule's segment durations are seconds
                command = self._active_command(cfg, (tick - warmup) * C.CONTROL_DT)
                if self.reference.T - self.reference.cursor < 12 or (tick - warmup) % cfg.replan_every == 0:
                    if self.reference.maybe_replan(
                            self.planner, reserve=10 ** 9,
                            context=self._context(mode=cfg.context_from),
                            mode=cfg.mode, movement=command["movement"], facing=command["facing"],
                            target_vel=command["target_vel"], height=cfg.height):
                        self._apply_crouch(cfg.crouch)
                action, q_des, _ = self.controller.act(self.reference, state["base_quat"])
                self.reference.advance()
            self.env.set_target(q_des)
            self.env.step()

            if tick >= warmup:
                state = self.env.state()
                log["t"].append(state and self.env.time)
                log["q_cmd"].append(self.reference.joint_pos[self.reference.cursor].copy())
                log["q_act"].append(state["q_hw"][C.MUJOCO_TO_ISAACLAB].copy())
                log["dq_act"].append(state["dq_hw"][C.MUJOCO_TO_ISAACLAB].copy())
                log["base_pos"].append(state["base_pos"].copy())
                log["base_quat"].append(state["base_quat"].copy())
                log["base_lin_vel"].append(state["base_lin_vel"].copy())
                log["base_ang_vel"].append(state["base_ang_vel"].copy())
                log["contact"].append(self._foot_contact())
                log["cmd"].append([command["target_vel"], *command["movement"][:2],
                                   *command["facing"][:2]])
                if len(log["t"]) % cfg.envelope_stride == 0:
                    # M(t) as the data pipeline wants it: the body surface seen from the pelvis,
                    # i.e. the frame every containment test in this project measures in. It must
                    # be stored as an *ellipsoid*, because that is the shape `EllipsoidManifold`
                    # measures: writing `max|rel|` per axis here stores a *box*, and using box
                    # half-extents as ellipsoid semi-axes puts the body's own points at
                    # r = 1.18-1.57 (measured, median 1.40), which made "inside the manifold"
                    # unsatisfiable by the very pose the envelope came from. `fit_ellipsoid`
                    # scales the half-extents by max_i ||rel_i/semi||, the smallest uniform
                    # inflation that contains the samples (verified: r = 1.0000). The same fit is
                    # applied by `recompute_envelopes`, so a fresh collection and a rewritten one
                    # agree instead of silently using different rulers.
                    pelvis = self.env.state()["base_pos"]
                    measured = read_landmarks(self.env.model, self.env.data, offsets)
                    rel = np.array([measured[n] - pelvis for n in sorted(offsets)])
                    env_t.append(float(self.env.time))
                    env_center.append(pelvis.copy())
                    env_semi.append(fit_ellipsoid(rel)["semi"])
                    env_top.append(float(pelvis[2] + rel[:, 2].max()))

        wall = time.perf_counter() - wall
        data = {k: np.array(v) for k, v in log.items()}
        data.update(envelope_t=np.array(env_t), envelope_center=np.array(env_center),
                    envelope_semi=np.array(env_semi), envelope_top=np.array(env_top))
        data["landmarks"] = np.array([read_landmarks(self.env.model, self.env.data, offsets)[n]
                                      for n in sorted(offsets)])
        summary = self._summary(cfg, data, wall)
        self.summary = summary
        return data

    def _active_command(self, cfg: ClipConfig, elapsed_s: float) -> dict:
        """The command in force at `elapsed` seconds: the schedule's segment, or the fixed one."""
        if not cfg.schedule:
            return {"movement": cfg.movement, "facing": cfg.facing, "target_vel": cfg.target_vel}
        t = 0.0
        for segment in cfg.schedule:
            t += segment.duration
            if elapsed_s < t:
                return {"movement": segment.movement, "facing": segment.facing,
                        "target_vel": segment.target_vel}
        last = cfg.schedule[-1]
        return {"movement": last.movement, "facing": last.facing, "target_vel": last.target_vel}

    def _apply_crouch(self, amount: float) -> None:
        """Offset every frame of the planned clip along the crouch direction (re-applied after
        each splice, which replaces the joint rows)."""
        if amount:
            self.reference.joint_pos = self.reference.joint_pos + float(amount) * CROUCH_DIRECTION[None, :]

    def _context(self, frames: int = 4, mode: str = "state") -> np.ndarray:
        """Planner context: the last few qpos rows (root xyz + quat + 29 joints, MuJoCo order).

        "state" feeds the planner where the robot actually is; "reference" feeds it the clip it
        is replaying (what the old loop did), which keeps the planner inside the commanded
        regime - the difference matters as soon as a crouch offset is in play.
        """
        if mode == "reference" and self.reference is not None:
            return self.reference.context_qpos(frames)
        state = self.env.state()
        qpos = np.concatenate([state["base_pos"], state["base_quat"], state["q_hw"]])
        return qpos[None, :].repeat(frames, axis=0)

    def _foot_contact(self) -> np.ndarray:
        """Which feet touch the floor right now (left, right)."""
        model, data = self.env.model, self.env.data
        floor = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_GEOM, "floor")
        feet = {mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, name): i
                for i, name in enumerate(("left_ankle_roll_link", "right_ankle_roll_link"))}
        flags = np.zeros(2, dtype=bool)
        for c in range(data.ncon):
            contact = data.contact[c]
            for g1, g2 in ((contact.geom1, contact.geom2), (contact.geom2, contact.geom1)):
                if g1 == floor and model.geom_bodyid[g2] in feet:
                    flags[feet[model.geom_bodyid[g2]]] = True
        return flags

    def _summary(self, cfg: ClipConfig, data: dict, wall: float) -> dict:
        err = np.abs(data["q_cmd"] - data["q_act"])
        base = data["base_pos"]
        quat = data["base_quat"]
        roll = np.degrees(np.arctan2(2 * (quat[:, 0] * quat[:, 1] + quat[:, 2] * quat[:, 3]),
                                     1 - 2 * (quat[:, 1] ** 2 + quat[:, 2] ** 2)))
        vx = data["base_lin_vel"][:, 0]
        vy = data["base_lin_vel"][:, 1]
        speed = np.linalg.norm(data["base_lin_vel"][:, :2], axis=1)
        yaw = np.degrees(np.arctan2(2 * (quat[:, 0] * quat[:, 3] + quat[:, 1] * quat[:, 2]),
                                    1 - 2 * (quat[:, 2] ** 2 + quat[:, 3] ** 2)))
        fell = bool(base[:, 2].min() < cfg.fall_height) or bool(np.abs(roll).max() > 60)
        forward = float(vx.sum() * C.CONTROL_DT)              # signed displacement, world x
        travelled = float(speed.sum() * C.CONTROL_DT)         # path length, any direction
        moved = (not fell) and travelled > cfg.walk_distance
        return {
            "config": json.loads(json.dumps(asdict(cfg))),   # tuples -> lists, for the JSON
            "ticks": int(len(data["t"])),
            "wall_time_s": wall,
            "fell": fell,
            "moved": moved,          # not fallen, and it actually travelled
            "track_err_mean_rad": float(err.mean()),
            "track_err_legs_rad": float(err[:, :12].mean()),
            "track_err_waist_rad": float(err[:, 12:15].mean()),
            "track_err_arms_rad": float(err[:, 15:].mean()),
            "base_z_mean": float(base[:, 2].mean()),
            "base_z_min": float(base[:, 2].min()),
            "vx_mean": float(vx[10:].mean()),
            "vy_mean": float(vy[10:].mean()),
            "speed_mean": float(speed[10:].mean()),
            "yaw_start_deg": float(yaw[0]),
            "yaw_end_deg": float(yaw[-1]),
            "yaw_change_deg": float(np.degrees(np.unwrap(np.radians(yaw))[-1] - np.radians(yaw[0]))),
            "roll_rms_deg": float(np.sqrt(np.mean(roll ** 2))),
            "forward_m": forward,
            "travelled_m": travelled,
            "contact_ratio": [float(x) for x in data["contact"].mean(axis=0)],
            "envelope_semi_mean": [float(x) for x in data["envelope_semi"].mean(axis=0)],
            "envelope_semi_min": [float(x) for x in data["envelope_semi"].min(axis=0)],
            "envelope_semi_max": [float(x) for x in data["envelope_semi"].max(axis=0)],
            "envelope_top_mean": float(data["envelope_top"].mean()),
        }

    def save(self, out_dir: Path, tag: str) -> tuple[Path, Path]:
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        npz = out_dir / f"{tag}.npz"
        np.savez_compressed(npz, **{k: v for k, v in self.last_data.items()
                                    if isinstance(v, np.ndarray)})
        js = out_dir / f"{tag}.json"
        js.write_text(json.dumps(self.summary | {"clip": tag}, indent=2))
        return npz, js


def main() -> int:
    parser = argparse.ArgumentParser(description="Record one SONIC-executed motion clip")
    parser.add_argument("--seconds", type=float, default=4.0)
    parser.add_argument("--mode", type=int, default=2)
    parser.add_argument("--target-vel", type=float, default=-1.0)
    parser.add_argument("--height", type=float, default=-1.0)
    parser.add_argument("--context-from", choices=("state", "reference"), default="state")
    parser.add_argument("--replan-every", type=int, default=5,
                        help="control ticks between planner calls (5 = 10 Hz)")
    parser.add_argument("--crouch", type=float, default=0.0,
                        help="joint-space crouch offset added to the planned gait")
    parser.add_argument("--movement", type=float, nargs=3, default=[1.0, 0.0, 0.0])
    parser.add_argument("--facing", type=float, nargs=3, default=[1.0, 0.0, 0.0])
    parser.add_argument("--out", type=Path, default=Path("reports/manifold_motion/clips"))
    parser.add_argument("--tag", default=None)
    args = parser.parse_args()

    cfg = ClipConfig(seconds=args.seconds, mode=args.mode, target_vel=args.target_vel,
                     height=args.height, movement=tuple(args.movement), crouch=args.crouch,
                     facing=tuple(args.facing), context_from=args.context_from,
                     replan_every=args.replan_every)
    recorder = ClipRecorder()
    data = recorder.run(cfg)
    recorder.last_data = data
    tag = args.tag or (f"mode{cfg.mode}_v{cfg.target_vel:+.2f}_c{cfg.crouch:.1f}"
                       f"_{cfg.context_from}")
    npz, js = recorder.save(args.out, tag)

    s = recorder.summary
    verdict = "fell" if s["fell"] else ("moved" if s["moved"] else "held still")
    print(f"{tag}: {s['ticks']} ticks in {s['wall_time_s']:.1f} s wall [{verdict}], "
          f"base_z {s['base_z_mean']:.3f} m, vx {s['vx_mean']:+.2f} m/s, "
          f"forward {s['forward_m']:.2f} m, path {s['travelled_m']:.2f} m")
    print(f"  tracking error: mean {s['track_err_mean_rad']:.4f} rad | legs "
          f"{s['track_err_legs_rad']:.4f} | waist {s['track_err_waist_rad']:.4f} | arms "
          f"{s['track_err_arms_rad']:.4f}")
    print(f"  contact ratio L/R {s['contact_ratio'][0]:.2f}/{s['contact_ratio'][1]:.2f}   "
          f"envelope semi {np.round(s['envelope_semi_mean'], 3).tolist()}   "
          f"top {s['envelope_top_mean']:.3f} m")
    print(f"saved {npz} and {js}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
