"""Render physically validated latent skills as a synchronized MuJoCo atlas.

Every panel is generated by the environment-conditioned latent prior, executed through the
frozen SONIC controller, and checked with the exact robot mesh against the static ellipsoid
corridor union.  The orange ellipsoid is the measured robot manifold ``M_self``; cyan is the
nearest environment-corridor element ``M_e``.  This intentionally differs from the older
geometry-router demos: no panel replays a hand-selected animation directly.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path

import mujoco
import numpy as np
from PIL import Image, ImageDraw, ImageFont

from manifold_motion.core import constants as C
from manifold_motion.dataio.seed_replay import ReplayConfig, SeedReplayRunner
from manifold_motion.planning.corridor import ExecutedEnvelopeEstimator, _resample_corridor
from manifold_motion.simulation.env import G1FlatEnv
from manifold_motion.stage2.render import _add_ellipsoid, _add_sphere, _local_to_world
from manifold_motion.stage2.validate import validate_trajectory


BACKGROUND = (12, 18, 27)
WHITE = (238, 244, 250)
MUTED = (164, 178, 194)
GREEN = (76, 224, 145)
RED = (255, 103, 92)


def _font(size: int, bold: bool = False):
    name = "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf"
    for path in (Path("/usr/share/fonts/truetype/dejavu") / name, Path(name)):
        try:
            return ImageFont.truetype(str(path), size)
        except OSError:
            pass
    return ImageFont.load_default()


@dataclass
class Case:
    label: str
    sample_path: Path
    sample: dict[str, np.ndarray]
    execution: dict[str, np.ndarray]
    summary: dict[str, object]
    corridor: np.ndarray
    corridor_world: np.ndarray
    self_semi: np.ndarray


def _parse_case(value: str) -> tuple[str, Path]:
    if "=" not in value:
        raise argparse.ArgumentTypeError("case must be LABEL=sample.npz")
    label, path = value.split("=", 1)
    if not label.strip() or not path.strip():
        raise argparse.ArgumentTypeError("case label/path must be non-empty")
    return label.strip(), Path(path)


def _load_case(label: str, path: Path, runner: SeedReplayRunner,
               envelope: ExecutedEnvelopeEstimator, max_radius: float) -> Case:
    with np.load(path) as archive:
        sample = {key: np.asarray(archive[key]) for key in archive.files}
    if "generated_ref" not in sample or "condition_corridor" not in sample:
        raise ValueError(f"{path} must contain generated_ref and condition_corridor")
    execution, summary = validate_trajectory(
        sample["generated_ref"], source=path, source_hz=30.0, config=ReplayConfig(),
        corridor=sample["condition_corridor"], max_corridor_radius=max_radius,
        stratum=label, runner=runner)
    corridor = _resample_corridor(sample["condition_corridor"], len(execution["q_exec"]))
    origin_pos, origin_quat = execution["base_pos"][0], execution["base_quat"][0]
    corridor_world = _local_to_world(corridor[:, :3], origin_pos, origin_quat)
    self_semi = envelope.sequence(execution["q_exec"], execution["base_pos"], execution["base_quat"])
    return Case(label, path, sample, execution, summary, corridor, corridor_world, self_semi)


def _root_yaw(quat: np.ndarray) -> float:
    forward = C.quat_rotate(quat, np.array([1.0, 0.0, 0.0]))
    return float(np.arctan2(forward[1], forward[0]))


def _render_panel(renderer: mujoco.Renderer, camera: mujoco.MjvCamera,
                  option: mujoco.MjvOption, env: G1FlatEnv, case: Case,
                  tick: int, width: int, height: int) -> Image.Image:
    execution = case.execution
    q = execution["q_exec"][tick]
    pos = execution["base_pos"][tick]
    quat = execution["base_quat"][tick]
    env.data.qpos[:3] = pos
    env.data.qpos[3:7] = quat
    env.data.qpos[env.body_qadr] = q[C.ISAACLAB_TO_MUJOCO]
    env.data.qpos[env.hand_qadr] = 0.0
    env.data.qvel[:] = 0.0
    mujoco.mj_forward(env.model, env.data)
    camera.lookat[:] = pos
    renderer.update_scene(env.data, camera=camera, scene_option=option)
    scene = renderer.scene
    for point in execution["base_pos"][max(0, tick - 100):tick:3]:
        _add_sphere(scene, point, 0.012, (1.0, 0.50, 0.08, 0.75))
    nearest = int(np.argmin(np.linalg.norm(case.corridor_world - pos[None], axis=1)))
    environment = case.corridor[nearest]
    _add_ellipsoid(scene, case.corridor_world[nearest], environment[3:6],
                   float(environment[6]), (0.10, 0.90, 0.95, 0.13))
    _add_ellipsoid(scene, pos, case.self_semi[tick], _root_yaw(quat),
                   (1.00, 0.45, 0.08, 0.17))
    image = Image.fromarray(np.asarray(renderer.render()), mode="RGB")
    draw = ImageDraw.Draw(image)
    draw.rectangle((0, 0, width, 76), fill=(8, 12, 18))
    accepted = bool(case.summary.get("accepted", False))
    status_color = GREEN if accepted else RED
    draw.text((10, 7), case.label, font=_font(19, True), fill=WHITE)
    draw.text((width - 65, 9), "PASS" if accepted else "FAIL",
              font=_font(15, True), fill=status_color)
    spatial = float(case.summary.get("corridor_radius_spatial_union_max", float("nan")))
    temporal = float(case.summary.get("corridor_radius_temporal_max", float("nan")))
    track = float(case.summary.get("track_err_mean_rad", float("nan")))
    draw.text((10, 33), f"mesh rho_static={spatial:.3f}   rho_time={temporal:.3f}",
              font=_font(13), fill=WHITE)
    draw.text((10, 53), f"track={track:.3f} rad   M_self={case.self_semi[tick].round(2).tolist()}",
              font=_font(12), fill=MUTED)
    return image


def render(args: argparse.Namespace) -> Path:
    runner = SeedReplayRunner(args.scene)
    envelope = ExecutedEnvelopeEstimator()
    cases = [_load_case(label, path, runner, envelope, args.max_corridor_radius)
             for label, path in args.case]
    columns = min(args.columns, len(cases))
    rows = int(math.ceil(len(cases) / columns))
    env = G1FlatEnv(args.scene)
    renderer = mujoco.Renderer(env.model, height=args.height, width=args.width)
    camera = mujoco.MjvCamera()
    mujoco.mjv_defaultCamera(camera)
    camera.type = mujoco.mjtCamera.mjCAMERA_TRACKING
    camera.trackbodyid = mujoco.mj_name2id(env.model, mujoco.mjtObj.mjOBJ_BODY, "pelvis")
    camera.distance, camera.azimuth, camera.elevation = args.distance, 125.0, -12.0
    option = mujoco.MjvOption()
    mujoco.mjv_defaultOption(option)
    output: list[Image.Image] = []
    try:
        for progress in np.linspace(0.0, 1.0, args.frames):
            canvas = Image.new("RGB", (columns * args.width, rows * args.height + 42), BACKGROUND)
            draw = ImageDraw.Draw(canvas)
            draw.text((12, 9),
                      "ENV-CONDITIONED LATENT SKILL ATLAS | cyan=M_e  orange=M_self  all panels=SONIC/MuJoCo",
                      font=_font(18, True), fill=WHITE)
            for index, case in enumerate(cases):
                tick = int(round(progress * (len(case.execution["q_exec"]) - 1)))
                panel = _render_panel(renderer, camera, option, env, case, tick,
                                      args.width, args.height)
                x, y = (index % columns) * args.width, 42 + (index // columns) * args.height
                canvas.paste(panel, (x, y))
            output.append(canvas.quantize(colors=128, method=Image.Quantize.MEDIANCUT))
    finally:
        renderer.close()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    output[0].save(args.out, save_all=True, append_images=output[1:],
                   duration=int(round(1000.0 / args.fps)), loop=0,
                   optimize=True, disposal=2)
    report = {
        "schema": "manifold-motion.latent-skill-atlas.v1",
        "out": str(args.out), "frames": args.frames, "fps": args.fps,
        "cases": [{"label": case.label, "sample": str(case.sample_path),
                   "accepted": bool(case.summary.get("accepted", False)),
                   "failed_checks": case.summary.get("failed_checks", []),
                   "corridor_radius_spatial_union_max": case.summary.get("corridor_radius_spatial_union_max"),
                   "corridor_radius_temporal_max": case.summary.get("corridor_radius_temporal_max"),
                   "track_err_mean_rad": case.summary.get("track_err_mean_rad")}
                  for case in cases],
    }
    report_path = args.report or args.out.with_suffix(".json")
    report_path.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))
    return args.out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", type=_parse_case, action="append", required=True,
                        help="repeatable LABEL=sample.npz latent candidate")
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--report", type=Path, default=None)
    parser.add_argument("--scene", type=Path, default=C.FLAT_SCENE)
    parser.add_argument("--max-corridor-radius", type=float, default=1.0)
    parser.add_argument("--columns", type=int, default=4)
    parser.add_argument("--width", type=int, default=360)
    parser.add_argument("--height", type=int, default=280)
    parser.add_argument("--frames", type=int, default=48)
    parser.add_argument("--fps", type=float, default=12.0)
    parser.add_argument("--distance", type=float, default=2.55)
    args = parser.parse_args()
    if len(args.case) < 2 or min(args.columns, args.width, args.height, args.frames, args.fps,
                                 args.max_corridor_radius) <= 0:
        parser.error("at least two cases and positive render/gate parameters are required")
    render(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
